spring.application.name=walletly-backend

spring.mongodb.uri=${MONGO_URI}

jwt.secret=${JWT_SECRET}

#1 days in millis
jwt.access.expiration=86400000

#2 days in millis
jwt.refresh.expiration=172800000

spring.data.redis.url=${REDIS_URI}
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms


logging.level.org.springframework.security=DEBUG

flutter.client.secret=${FLUTTER_CL_SECRET}
flutter.webhook.secret=${FLUTTER_WH_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=udehchisom001@gmail.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true
