spring.application.name=walletly-backend

spring.mongodb.uri=mongodb+srv://leonwokedichisom_db_user:wd1yDcmQAVpjLxGR@cluster0.yeh9zjo.mongodb.net/walletly?retryWrites=true&w=majority&appName=Cluster0

jwt.secret=idontknow091what256bitis!theysayit's32characters,isthislongenoughforyou???

#1 days in millis
jwt.access.expiration=86400000

#2 days in millis
jwt.refresh.expiration=172800000

spring.data.redis.url=rediss://default:gQAAAAAAAhStAAIgcDIwZmE0ZjI5MDBmMTA0OTVmOGIzOTg5ZjNiMTJiYmRmMw@feasible-halibut-136365.upstash.io:6379
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms


logging.level.org.springframework.security=DEBUG

flutter.client.secret=FLWSECK_TEST-1a13a0557f7cfc5ae20141467bce5354-X
flutter.webhook.secret=nFu9hpwF!8h6pEn

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=udehchisom001@gmail.com
spring.mail.password=nlgshwtfygblyvxd
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true
