spring.application.name=walletly-backend

spring.mongodb.uri=mongodb://localhost:27017/walletly
resend.api.key=re_9Qxd75Ku_LWpu8mTaH4DGSukNEVVb7MYL

jwt.secret=idontknow091what256bitis!theysayit's32characters,isthislongenoughforyou???
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

logging.level.org.springframework.security=DEBUG