import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Walletly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} md:px-20 md:py-7 py-5 px-3 antialiased overflow-x-hidden`}
      >
        <div className="fixed size-120 blur-3xl rounded-full md:-bottom-50 -top-50 -left-30 bg-primary -z-10 opacity-10" />

        {children}

        <div className="fixed size-120 blur-3xl rounded-full md:-bottom-50 -bottom-100 -right-10 bg-primary -z-10 opacity-10" />
      </body>
    </html>
  );
}
